Algoritmo "ParEImpar"
// algoritmo que leia um nº inteiro e mostre uma mensagem indicando se este número é par ou ímpar, e se é positivo ou negativo.


Var

//Entrada:
n:inteiro
//Processamento:

//Saida:


Inicio

escreval("Informe um número inteiro.")
leia (n)

se (n % 2 = 0 ) entao
escreval("O número", n, " é par.")

senao
escreval("O número", n, " é ímpar.")

fimse



Fimalgoritmo